// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ8atzEBxvjBh_pQYFoAJsIgWX3dgY0Es',
    appId: '1:495136441834:web:93c7fdfc12871ffbbf1e93',
    messagingSenderId: '495136441834',
    projectId: 'evently-fri',
    authDomain: 'evently-fri.firebaseapp.com',
    storageBucket: 'evently-fri.firebasestorage.app',
    measurementId: 'G-N7PHQVJ3R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Wviyjb1XnA3poQGEJ3DdpO2VncuRNBs',
    appId: '1:495136441834:android:30343008823bb29bbf1e93',
    messagingSenderId: '495136441834',
    projectId: 'evently-fri',
    storageBucket: 'evently-fri.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKhGBYTPbNgmIrNdsN_e2BQFHrzjSr4sY',
    appId: '1:495136441834:ios:6dd10251e7731eeabf1e93',
    messagingSenderId: '495136441834',
    projectId: 'evently-fri',
    storageBucket: 'evently-fri.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKhGBYTPbNgmIrNdsN_e2BQFHrzjSr4sY',
    appId: '1:495136441834:ios:6dd10251e7731eeabf1e93',
    messagingSenderId: '495136441834',
    projectId: 'evently-fri',
    storageBucket: 'evently-fri.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ8atzEBxvjBh_pQYFoAJsIgWX3dgY0Es',
    appId: '1:495136441834:web:f5475a519da5bca0bf1e93',
    messagingSenderId: '495136441834',
    projectId: 'evently-fri',
    authDomain: 'evently-fri.firebaseapp.com',
    storageBucket: 'evently-fri.firebasestorage.app',
    measurementId: 'G-XY3QT097BX',
  );
}
